name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '16'

    - name: Install NPM Dependencies
      run: npm ci

    - name: Compile Assets
      run: npm run build

    - name: Deploy  Laravel(Production)
      if: success() && github.ref == 'refs/heads/main'
      run: | 
           curl -X POST https://blast-mail-production.up.railway.app/
